version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Serverless Framework...
      - npm install -g serverless
      - echo Installing project dependencies...
      - npm install
  pre_build:
    commands:
      - echo Configure AWS CLI...
      - aws configure set AWS_CREDENTIALS_ACCESS_KEY $AWS_CREDENTIALS_ACCESS_KEY
      - aws configure set AWS_CREDENTIALS_SECRET_KEY $AWS_CREDENTIALS_SECRET_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
      - export AWS_ACCESS_KEY_ID=$AWS_CREDENTIALS_ACCESS_KEY
      - export AWS_SECRET_ACCESS_KEY=$AWS_CREDENTIALS_SECRET_KEY
  build:
    commands:
      - npm run build
      - serverless deploy
  post_build:
    commands:
      - ./scripts/update-apigetway.sh
